# Generated by Django 4.0.4 on 2022-05-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a club competiton (e.g. sci-fi, comedy)', max_length=50, unique=True, verbose_name='Competiton name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Klub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Info')),
                ('established', models.DateField(blank=True, help_text='Please use the following format: <em>YYYYMM-DD</em>.', null=True, verbose_name='Established')),
                ('domestic_champions', models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='DChampions')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='klub/logo/%Y/%m/%d/', verbose_name='Logo')),
                ('europe_rating', models.IntegerField(blank=True, help_text='Please enter an integer value (minutes)', null=True, verbose_name='ERating')),
                ('competitions', models.ManyToManyField(help_text='Select a competitions for this club', to='kluby.competition')),
            ],
            options={
                'ordering': ['europe_rating', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
