# Generated by Django 4.0.4 on 2022-05-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0002_competition_klub_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='nation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nation'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='Enter a club competiton (e.g. Champions league, LaLiga)', max_length=50, unique=True, verbose_name='Competiton name'),
        ),
        migrations.AlterField(
            model_name='klub',
            name='domestic_champions',
            field=models.IntegerField(blank=True, help_text='Please enter an integer value', null=True, verbose_name='League titles'),
        ),
        migrations.AlterField(
            model_name='klub',
            name='europe_rating',
            field=models.IntegerField(blank=True, help_text='Please enter an integer value', null=True, verbose_name='Europe rank'),
        ),
    ]
