# Generated by Django 4.0.4 on 2022-06-06 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0004_alter_competition_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='klub',
            name='champions_league',
            field=models.IntegerField(blank=True, help_text='Please enter an integer value', null=True, verbose_name='Champions League'),
        ),
        migrations.AddField(
            model_name='klub',
            name='europa_league',
            field=models.IntegerField(blank=True, help_text='Please enter an integer value', null=True, verbose_name='Europa League'),
        ),
    ]
