# Generated by Django 4.0.4 on 2022-06-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kluby', '0005_klub_champions_league_klub_europa_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='nation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nation'),
        ),
        migrations.AddField(
            model_name='klub',
            name='stadium',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stadium'),
        ),
    ]
